name: aziz_bookstore
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_gemini: ^2.0.4
  flutter_inappwebview: ^6.0.0
  flutter_markdown: ^0.7.2+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  lottie: ^3.1.2
  path: ^1.9.0
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1

dev_dependencies:
  build_runner: ^2.4.6
  bloc_test: ^9.1.7
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  mockito: ^5.0.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - .env
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/play_store_512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/play_store_512.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/splash.png
  android_12:
    image: assets/icons/splash_andro.png
    icon_background_color: "#ffffff"
    image_dark: assets/icons/splash_andro.png
    icon_background_color_dark: "#121212"

  web: false